# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SuSiE_group <- function(y, X1, X2, L, f = 1, delta = 0.001, maxIt = 100L) {
    .Call(`_CPSuSiE_SuSiE_group`, y, X1, X2, L, f, delta, maxIt)
}

