# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SER <- function(y, X, XX, sigma2, sigma2_0, pi_0) {
    .Call(`_CPSuSiE_SER`, y, X, XX, sigma2, sigma2_0, pi_0)
}

SuSiE_group <- function(y, X1, X2, L, delta = 0.001, maxIt = 100L) {
    .Call(`_CPSuSiE_SuSiE_group`, y, X1, X2, L, delta, maxIt)
}

